### ISSUE TITLE
Добавить существам отталкивание от границ окна

### ISSUE THREAD

**Issue by cblp** [haskarium/haskarium#12]

**Comment by arwynn** [comment]
А можно тут же добавить отталкивание от границ окна? А то они расползаются шустро :(

**Comment by cblp** [comment]
да

**Comment by iloskutov** [comment]
Пока реализовал отталкивание от границ окна, живность теперь не расползается.
Чуть позже добавлю запрет наползаний друг на друга. Или можно попробовать разделить эти задачи.

**Comment by wiz** [comment]
Да, лучше разделить.

**Comment by cblp** [comment]
resolved in #22
