### ISSUE TITLE
Выделить стейт симуляции из мира

### ISSUE THREAD

**Issue by wiz** [haskarium/haskarium#31]
Сейчас рандом лежит на одной полке с обитателями мира и получаются костыли вроде подсовывания финального стдгена в мир после его создания. При этом сервис рандома в симуляторе может использоваться для любого из миров, которые в нём могут гоняться.

```
exe/Haskarium/Generate.hs
31:    <*> pure dummyGen -- FIXME: extract to simulation state
```

Частным решением может быть добавление примитива, выдающего текущий ген в качестве результата. Но это костылище т.к. нет гарантий, что после него не будет ещё операций.

**Comment by cblp** [comment]
Да, проще всего описывать состояние игры парой — состояние мира и состояние генратора.

**Comment by wiz** [comment]
Рандом переехал из `World` в `State StdGen`.
